name: Update GitHub Stats

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Update README with stats
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          python update_readme.py $GITHUB_USERNAME $GITHUB_TOKEN README.md

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats [skip ci]" && git push)
