name: Update GitHub Stats

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual trigger from Actions tab

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper pull/push
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Update README with stats
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: |
          python update_readme.py $GITHUB_USERNAME $GITHUB_TOKEN README.md

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md

          # Check if there are changes
          if ! git diff --quiet --staged; then
            # Pull latest changes with rebase to avoid merge commits
            git pull --rebase origin master || {
              echo "Pull failed, attempting to resolve..."
              git rebase --abort 2>/dev/null || true
              git pull --no-rebase origin master
            }

            # Commit and push changes
            git commit -m "Update GitHub stats [skip ci]"

            # Retry push up to 3 times if it fails
            for i in {1..3}; do
              if git push; then
                echo "Successfully pushed changes"
                exit 0
              else
                echo "Push failed, attempt $i of 3. Pulling latest changes..."
                git pull --rebase origin master || git pull --no-rebase origin master
                sleep 2
              fi
            done

            echo "Failed to push after 3 attempts"
            exit 1
          else
            echo "No changes to commit"
          fi
